# Generated by Django 2.1 on 2018-11-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0004_fotodenoticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Descrição'),
        ),
    ]
